server:
  port: 19984
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: glddld4@gmail.com
    password: rladlrwn89@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rladlrwn89
    url: jdbc:mysql://localhost:3306/toy
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 10
      max-lifetime: 120000
      auto-commit: false
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    jdbc.resultsettable: INFO
    org.springframework.web: INFO
  file:
    name: ${file.separator}logs${file.separator}toprojectapi.log
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 10MB